# Generated by Django 5.1.5 on 2025-01-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('category', models.CharField(choices=[('EB', 'Earbuds'), ('SW', 'Smart Watch'), ('MS', 'Mouse'), ('SB', 'Sound Box'), ('RT', 'Router'), ('SF', 'Stand Fan'), ('PT', 'Printer'), ('KB', 'Keyboard'), ('HP', 'Headphone')], max_length=2)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products')),
            ],
        ),
    ]
