# Generated by Django 5.2.1 on 2025-06-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created'], 'verbose_name_plural': 'Categories'},
        ),
    ]
